# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mac服务器' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Mac服务器

  target 'Mac服务器Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mac服务器UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'CocoaAsyncSocket'
end
